#!/usr/bin/env python
#找出每个键对最大值
#mapreduce框架保证键对有序性

import sys

(last_key,max_val) = (None,-sys.maxint)
for line in sys.stdin:
    (key,val) = line.strip().split("\t")
    if last_key and last_key != key:                          #每当key变化时，说明一组key处理完－－由mapreduce框架保证，存shell测试时，应该使用sort保证key对有序性
        print("%s\t%s"%(last_key,max_val))                    #键值不存在时，输出键值
        (last_key,max_val) = (key,int(val))                   #存储键值
    else:
        (last_key,max_val) = (key,max(max_val,int(val)))      #键值存在时，存储更新键值
if last_key:
    print("%s\t%s"%(last_key,max_val))
